sigma2: 0.1
epsilon: 0.5
train_rate: 0.8
seq_len: 12
pre_len: 6
dropout: 0.4
gc_layer_sizes:
  - 32
  - 10
gc_activations:
  - "relu"
  - "relu"
lstm_layer_sizes:
  - 200
  - 200
lstm_activations:
  - "relu"
  - "relu"
epochs: 1000
batch_size: 60
model_name: "Model_Adam_0001"
optimizer_name: "Adam"
learning_rate: 0.0001
momentum: 0.7